add: PreloaderModal and integrated to the Toolbar
3DStreet/3dstreet-editor pull request #81
Opened 2022-12-06 16:22 UTC by omedvediev

2022-12-08 00:20 UTC, kfarr requested changes
@omedvediev 
* I left one comment asking about the 2.5 second timeout -- is there no method to remove the save dialog only when file downloaded?
* Also can we change the name from "PreloaderModal" to "SavingModal"? Reason being, we will later have a loading modal for the entire application which is different than this saving indicator.

2022-12-08 00:20 UTC, kfarr commented on src/components/scenegraph/Toolbar.js
> +      setTimeout(() => resolve(), 2500);
why wait 2500 ms? is there not a mechanism to wait to remove the saving modal until the file is downloaded?

2022-12-20 15:43 UTC, omedvediev commented on src/components/scenegraph/Toolbar.js
> +      setTimeout(() => resolve(), 2500);
Hello @kfarr !

2022-12-23 09:38 UTC, omedvediev commented
Hello, @kfarr, I've reduced timeout to 1s, and renamed PreloaderModal to SavingModal

2022-12-27 22:31 UTC, kfarr approved these changes

2022-12-27 22:32 UTC, kfarr commented
Thanks @omedvediev the last request is it possible to actually keep the loader up until the snapshot is actually completed and downloaded, for example with some sort of callback? A timeout is not a great solution IMHO but if that's the only thing possible right now it is at least better than nothing.

2022-12-29 08:40 UTC, omedvediev commented
Hello, @kfarr! Ok, I'm investigating possible solutions.

2023-01-02 14:28 UTC, omedvediev commented
Hello @kfarr , it looks like 'setTimeout' is the best solution for now. As the Browser's file downloading is beyond the scope of the Web App, I haven't found any solution for download finish detection for React.

2023-01-02 23:55 UTC, kfarr commented
@omedvediev thanks for the research. Understood it's easiest to stick with setTimeout, at least for a first version.

To finish this out:
* Can you set it for 2 seconds, instead of 1?
* Can you also rebase this / resolve conflicts? I started down the path to do that myself but honestly there are too many conflicts so I don't know how to make it work.

For future reference: (KF TODO make a new ticket for this)
* The primary cause of the delay is a-frame / three.js screencapture function. It should be possible to callback on this or related. It may not be possible to get a callback from the built-in a-frame function, so instead we may need to copy and modify our own.
* After the generation is done, then the file is downloaded. At this point there could be different indication to user that the generation is complete and that downloading is the next step, perhaps including instructions on how to approve browser user agent asking for download permission.

2023-01-03 09:26 UTC, omedvediev commented
Hello @kfarr , timeout is set to 2sec, conflicts are resolved.

2023-01-04 01:18 UTC, merged